### ISSUE TITLE
Custom links on AppInfo have highest priority

### ISSUE THREAD

**Issue by deletescape** [TheAndroidMaster/Attribouter#19]
When adding a custom link to the AppInfo it will automatically have the highest priority and thus appear on the left side of the list. A work around for this would currently be to just set the priority to `-1` but this isn't the cleanest solution.

**Comment by TheAndroidMaster** [comment]
All of the link priorities default to 0, so they _should_ be being sorted alphabetically (the auto generated links in appInfo also have a priority of 0). I'll test it some more later.

**Comment by TheAndroidMaster** [comment]
I HAVE FOUND THE PROBLEM

They are being sorted alphabetically, but it isn't getting the string resources first. So string resources starting with "^" or "@" are being displayed before the others. Proof: ("rate" is a string resource)
![image](https://user-images.githubusercontent.com/13000407/39717003-f9beede6-51ff-11e8-9721-25c697a00a3c.png)

**Comment by TheAndroidMaster** [comment]
So yes, you will still have to specify a negative number as the priority if you want custom links to appear at the end of the list, but they should at least sort properly now.

**Comment by deletescape** [comment]
That's perfect this way, atleast it makes sense in some way now 😉
