### ISSUE TITLE
Contributors with custom links aren't merged after fetching from Github

### ISSUE THREAD

**Issue by deletescape** [TheAndroidMaster/Attribouter#27]
![image](https://user-images.githubusercontent.com/13785669/39760493-b8c9f23c-52d5-11e8-9287-82ae3fe1b098.png)

**Comment by deletescape** [comment]
Might not actually be related to the links, it just seems to happen with a few random persons

**Comment by TheAndroidMaster** [comment]
I've found the problem. Attribouter doesn't check for capitalization of the login name. Since [api.github.com](https://api.github.com/users/joshuabaldassarre) returns the username as "JoshuaBaldassarre", it doesn't know which user to merge it into and ends up just making a new item.

**Comment by TheAndroidMaster** [comment]
I spent so long trying to fix this I feel like an idiot now for not seeing it before.

**Comment by TheAndroidMaster** [comment]
I'm not going to put this in its own release because it's kind of trivial and can be resolved pretty easily, so it'll have to wait until I either do #22 or find something else that's more important.

**Comment by TheAndroidMaster** [comment]
Okay, #24 has given me a reason to make a new version of the library now.
