### ISSUE TITLE
View Open Source Licences bug

### ISSUE THREAD

**Issue by adrcotfas** [TheAndroidMaster/Attribouter#39]
Great library!

I found a bug with the following settings:
```
    <licenses
        overflow="0"
        showDefaults="false">
        <project repo="TheAndroidMaster/Attribouter" />
    </licenses>
```
the title of the section appears as "View @string/title_attribouter_licences".
The bug does not appear if I remove the overflow attribute.
I seems that for the translators section, for example, this bug does not appear if I set the overflow to 0.

**Comment by TheAndroidMaster** [comment]
Huh. Possible workaround is to just set the 'title' attribute to "Open Source Licenses", which is the value of that string resource. I likely just overlooked something when I wrote it, I'll try and fix it properly tomorrow.
