### ISSUE TITLE
Feature request: possibility to disable description in appInfo

### ISSUE THREAD

**Issue by adrcotfas** [TheAndroidMaster/Attribouter#40]
It would be nice to have something like this without setting `description="^">` which, of course, maintains the extra space.

**Comment by TheAndroidMaster** [comment]
I'm currently in Iceland and can't get my laptop to log onto wifi so I won't be able to push until I get back (also there'll be a MERGE CONFLICT YAY), but (just for documentation and to show that I've actually done something with my life) the solution to this will be to remove the view when `description` is `@null` (or `^@null` to override GitHub).
