### ISSUE TITLE
Feature request: theme support

### ISSUE THREAD

**Issue by adrcotfas** [TheAndroidMaster/Attribouter#41]
Overwriting `@style/AttribouterTheme` is an option but it has its limitations if you have multiple themes in your app which can be switched.
I tried creating a separate Activity and then attach an About fragment to it which is great because you can switch the theme in onCreate.
```
        if (savedInstanceState == null) {
            Fragment fragment = Attribouter.from(this).withFile(R.xml.about).toFragment();

            FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
            ft.replace(R.id.fragment, fragment);
            ft.commitAllowingStateLoss();
        }
```
Unfortunately the theme is not maintained to a section with overflow "0" which opens a new view.
Is there a solution for this?

**Comment by TheAndroidMaster** [comment]
This is half a bug and half an enhancement idk what to label it

**Comment by TheAndroidMaster** [comment]
I don't even use labels I shouldn't be thinking about this. Anyway, the theme isn't applied because the "overflow" screens are actually fullscreen dialogs, and I'm not quite sure how I should make them themable. My initial thought is to set the dialog themes as an attribute of the activity theme (possibly two attributes, one for profile dialogs and one for overflows), but idk how easy that would be to implement.

**Comment by adrcotfas** [comment]
How is this supposed to be used?
I tried modifying the theme inside the sample app and it still uses the `AttribouterTheme`.

**Comment by TheAndroidMaster** [comment]
@adrcotfas you can override the AttribouterTheme in your app's styles.xml. That's the method I wrote in [the docs](https://jfenn.me/Attribouter/THEMING.html), anyway. You could also declare the Attribouter's activity in your manifest, add `tools:replace="android:theme"`, and specify your own resource there.

**Comment by adrcotfas** [comment]
I have multiple themes in my app which are changeable with a preference.
Overriding the AttribouterTheme is not an option for me because of this.
About declaring the Attribouter's activity in the manifest, I didn't quite understand if you mean the library's activity or my own about activity.

**Comment by adrcotfas** [comment]
> create your own activity for Attribouter, then call setTheme() before adding Attribouter's fragment (obtained from Attribouter.from(context).toFragment()) to your layout.

That's exactly what I'm doing but the dialogs will use the default or the overridden theme in this case.

**Comment by fennifith** [comment]
Whoa, I didn't respond to this. Were you able to get it working? I can verify that my suggestion works fine on my end; you can see a working example in [Status](https://github.com/fennifith/Status/blob/master/app/src/main/java/com/james/status/activities/AttribouterActivity.java), which currently has a dark theme in the beta channel.

I may reopen this to improve the functionality, though, as this method of theming is a little finicky. Maybe provide a default light/dark theme, then have two methods such as `.withTheme(int)` and `.withDarkTheme(boolean)`? Idk.

**Comment by adrcotfas** [comment]
@fennifith No worries but I stopped using this library in the end.
