### ISSUE TITLE
Remove hardcoded prefix word in Licences and Translators wedges when overflow is 0

### ISSUE THREAD

**Issue by adrcotfas** [TheAndroidMaster/Attribouter#47]
Hi,
Setting a custom title, I would expect to see that string without a prefix in front of it.

```
<me.jfenn.attribouter.wedges.LicensesWedge
    overflow="0"
    title="Open Source Licences"
    showDefaults="false">
    <me.jfenn.attribouter.wedges.LicenseWedge repo="TheAndroidMaster/Attribouter" />
</me.jfenn.attribouter.wedges.LicensesWedge>
```

will produce "**View** Open Source Licences".
Removing the overflow="0" will produce the desired string of "Open Source Licences".

**Comment by TheAndroidMaster** [comment]
It's not *actually* hardcoded, there is a string resource you could override, but fair enough, I can't actually remember what my reason for doing this was anyway.

**Comment by adrcotfas** [comment]
Thanks! It will be consistent in both states (with and without overflow 0) then.
