### ISSUE TITLE
Open GitHub profile if there is no website

### ISSUE THREAD

**Issue by deletescape** [TheAndroidMaster/Attribouter#8]
For contributors with no bio or website nothing happens if you click on them as of now, but it would make more sense if their GitHub profile would be opened

**Comment by TheAndroidMaster** [comment]
Huh, I thought I'd already accounted for that. Maybe I only did that in my head. Next release will have it.

_Should this be labeled as a bug or an enhancement? I'm confused._

**Comment by TheAndroidMaster** [comment]
Eh, I'll just give it both.
